name: 'Build, Test and Deploy Gradle Project'

on: 
    push:
        branches: [main]

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
        - name: Checkout code
          uses: actions/checkout@v4

        - name: Deploy Local MySQL Server
          run: './docker.sh'
        
        - name: Set up JDK 22
          uses: actions/setup-java@v4
          with:
            java-version: '22'
            distribution: 'temurin'
        
        - name: Setup Gradle
          uses: gradle/gradle-build-action@v2
        
        - name: Gradle Wrapper
          run: gradle wrapper
            
        - name: Build with Gradle
          run: ./gradlew build
        
        - name: Test with Gradle
          run: ./gradlew test
                


