name: 'Build, Test and Deploy Gradle Project'

on: 
    push:
        branches: [main]

jobs:
    build:
        runs-on: ubuntu-latest
        container:
            image: gradle:jdk17
        steps:
            - name: Checkout code
              uses: actions/checkout@v4
            
            - name: Deploy Local MySQL Server
              run: |
                docker run -it --rm \
                -p 3306:3306 \
                -e MYSQL_DATABASE=mn_playground \
                -e MYSQL_ROOT_PASSWORD=password \
                -e MYSQL_ALLOW_EMPTY_PASSWORD=true \
                mysql:8
          
            - name: Build with Gradle
              run: ./gradlew build
            
            - name: Test with Gradle
              run: ./gradlew test
            


